"""Add borrowed_days to  books 

Revision ID: 0e65f120d1df
Revises: 8a1e7151bb32
Create Date: 2025-06-13 11:37:24.289726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e65f120d1df'
down_revision: Union[str, None] = '8a1e7151bb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('books', sa.Column('borrow_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('books', 'borrow_days')
    # ### end Alembic commands ###
