"""remove field to book requests

Revision ID: a90bae6fb97c
Revises: f654ea6b7455
Create Date: 2025-06-12 17:29:06.966380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90bae6fb97c'
down_revision: Union[str, None] = 'f654ea6b7455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('requests', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('requests', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('requests', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('requests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
